// src/pages/fortnite-logos.tsx
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { Button } from "~/component/Button"; // Your themed Button component
import { FaChevronRight, FaMagic, FaDownload, FaPaintBrush } from "react-icons/fa";

// This is an array of style previews specifically for Fortnite.
// You would get these from your `gamerStylesData` where the subcategory is "Fortnite".
// For this page, we define it directly for clarity.
const fortniteStyleExamples = [
  // ** REPLACE these with ACTUAL paths to your best Fortnite-style example images **
  { src: "/styles/s643e.webp", alt: "AI generated cartoonish Fortnite logo with a llama" },
  { src: "/styles/s650e.webp", alt: "Vibrant and colorful Fortnite clan logo created with AI" },
  { src: "/styles/s640e.webp", alt: "Custom Fortnite gaming logo with bold text and a pickaxe" },
  { src: "/styles/s645e.webp", alt: "Free Fortnite logo maker example with a dynamic character" },
  { src: "/styles/s648e.webp", alt: "Fortnite YouTube logo with a playful mascot design" },
  { src: "/styles/s642e.webp", alt: "Esports team logo with a Fortnite inspired theme" },
  { src: "/styles/s647e.webp", alt: "Cool Fortnite clan logo with bright colors" },
  { src: "/styles/s646e.webp", alt: "Custom logo for a Fortnite gaming channel" },
];


const FortniteLogoLandingPage: NextPage = () => {
  const router = useRouter();

  const handleStartDesigning = () => {
    // This will navigate to your actual tool page.
    // Ideally, with parameters to pre-select the Fortnite style category.
    // Example: /gaming-logo-tool?category=By+Game+Title&subcategory=Fortnite
    void router.push("/gaming-logo-maker"); // Update if your tool can be pre-filtered
  };

  return (
    <>
      <Head>
        <title>Fortnite Logo Maker - Free AI Fortnite Clan & YouTube Logos | GamingLogoAI</title>
        <meta
          name="description"
          content="Create custom Fortnite logos for your clan, YouTube channel, or profile with our free AI Fortnite logo maker. Design unique, cool Fortnite gaming logos in seconds!"
        />
        <meta name="keywords" content="fortnite logo maker, fortnite logos, fortnite clan logo, free fortnite logo, custom fortnite logo, gaming logo fortnite, fortnite youtube logo, esports logo fortnite" />
        <link rel="canonical" href="https://gaminglogoai.com/fortnite-logos" /> {/* ** REPLACE with your actual domain ** */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white dark:bg-slate-950 text-slate-800 dark:text-slate-200 overflow-x-hidden">
        {/* Hero Section */}
        <section className="relative py-16 md:py-24 text-center text-white overflow-hidden">
          <Image src="/images/features/fortnite-hero-bg.webp" alt="Vibrant Fortnite-inspired background with storm clouds and llamas" layout="fill" objectFit="cover" quality={75} className="z-0 opacity-40 dark:opacity-30" priority />
          <div className="absolute inset-0 bg-gradient-to-br from-purple-800/80 via-blue-900/90 to-slate-900/95 z-10"></div>
          
          <div className="container mx-auto px-4 sm:px-6 relative z-20">
            <Image
              src="/styles/s641e.webp" // ** A great single Fortnite logo example **
              alt="A cool Fortnite clan logo generated by AI"
              width={150}
              height={150}
              className="mx-auto mb-6 rounded-lg shadow-2xl border-4 border-cyan-400/80"
              priority
            />
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold mb-6 leading-tight drop-shadow-lg">
              AI <span className="text-cyan-400">Fortnite Logo</span> Maker
            </h1>
            <p className="text-lg sm:text-xl text-slate-200 max-w-3xl mx-auto mb-10 drop-shadow-sm">
              Instantly generate unique logos for your Fortnite clan, team, or YouTube channel. Create a custom look that’s as vibrant and dynamic as the game itself!
            </p>
            <button
              onClick={handleStartDesigning}
              className="px-8 py-4 bg-gradient-to-r from-cyan-500 to-blue-500 text-slate-900 font-bold rounded-lg text-lg hover:from-cyan-600 hover:to-blue-600 transition-all duration-300 ease-in-out transform hover:scale-105 shadow-xl hover:shadow-cyan-500/50 focus:outline-none focus:ring-4 focus:ring-cyan-300 focus:ring-opacity-50"
              id="cta-hero-fortnite-to-tool"
            >
              Make Your Fortnite Logo <FaChevronRight className="inline ml-2 -mr-1" />
            </button>
            <p className="mt-4 text-xs text-slate-400">Start with 1 Free Credit.</p>
          </div>
        </section>

        {/* Example Gallery Section */}
        <section className="py-16 md:py-20 bg-white dark:bg-slate-900">
          <div className="container mx-auto px-4 sm:px-6">
            <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12 text-slate-900 dark:text-white">
              Get Inspired by AI-Generated <span className="text-purple-600 dark:text-cyan-400">Fortnite Logos</span>
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {fortniteStyleExamples.map((example, index) => (
                <div key={index} className="group relative rounded-lg shadow-lg overflow-hidden aspect-square">
                  <Image src={example.src} alt={example.alt} layout="fill" objectFit="cover" className="transition-transform duration-500 group-hover:scale-110" />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section className="py-16 md:py-20 bg-slate-50 dark:bg-slate-950">
            <div className="container mx-auto px-4 sm:px-6">
                <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12 text-slate-900 dark:text-white">
                    Create Your Custom <span className="text-purple-600 dark:text-cyan-400">Fortnite Clan Logo</span> in 3 Steps
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
                    {[
                        { title: "1. Enter Your Name", desc: "Type your clan or channel name. It's the star of the show!", icon: <FaMagic className="h-10 w-10 mx-auto mb-3"/> },
                        { title: "2. Pick a Fortnite Style", desc: "Choose from dozens of vibrant, cartoonish, and epic styles inspired by the game.", icon: <FaPaintBrush className="h-10 w-10 mx-auto mb-3"/> },
                        { title: "3. Generate & Download", desc: "Our AI creates your logos instantly. Download your favorite!", icon: <FaDownload className="h-10 w-10 mx-auto mb-3"/> }
                    ].map(step => (
                        <div key={step.title} className="p-6 bg-white dark:bg-slate-800 rounded-lg shadow-lg">
                            <div className="text-purple-600 dark:text-cyan-400">{step.icon}</div>
                            <h3 className="text-xl font-semibold my-2 text-slate-800 dark:text-white">{step.title}</h3>
                            <p className="text-sm text-slate-600 dark:text-slate-400">{step.desc}</p>
                        </div>
                    ))}
                </div>
                 <div className="text-center mt-12">
                    <button onClick={handleStartDesigning} className="px-8 py-4 bg-gradient-to-r from-cyan-500 to-blue-500 text-slate-900 font-bold rounded-lg text-lg hover:from-cyan-600 hover:to-blue-600 transition-all duration-300 ease-in-out transform hover:scale-105 shadow-xl hover:shadow-cyan-500/50 focus:outline-none focus:ring-4 focus:ring-cyan-300 focus:ring-opacity-50">
                        Start Designing for Free
                    </button>
                </div>
            </div>
        </section>
        
        {/* FAQ Section (Crucial for SEO) */}
        <section className="py-16 md:py-20 bg-white dark:bg-slate-900">
          <div className="container mx-auto max-w-3xl px-4 sm:px-6">
            <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12 text-slate-900 dark:text-white">
              Your <span className="text-purple-600 dark:text-cyan-400">Fortnite Logo</span> Questions Answered
            </h2>
            <div className="space-y-6">
              {[
                {
                  q: "Is this Fortnite logo maker really free?",
                  a: "Yes, you can get started for free! Every new user receives 1 free credit, which is enough to generate your first high-quality logo concept. You can experiment with the tool and see what it can do. If you want to create more variations or designs, you can easily purchase additional credit packs."
                },
                {
                  q: "Can I use these logos for my YouTube or Twitch channel?",
                  a: "Absolutely! The downloaded logos are perfect for use as a Fortnite YouTube logo, Twitch profile picture, or for your gaming channel's branding. The high-resolution files look great on any platform."
                },
                {
                  q: "How do I create a logo for my Fortnite clan?",
                  a: "It's simple! Just enter your clan name in our Fortnite clan logo maker, browse the styles inspired by the game's aesthetic, and let our AI generate options. You can create a professional-looking Fortnite clan logo in just a few minutes."
                },
                {
                  q: "Can I get a Fortnite logo without text?",
                  a: "Yes. While our tool is optimized for creating logos with text, you can try leaving the text field blank or using a single space. Some styles will generate awesome mascots or emblems that work well as a gaming logo without text."
                }
              ].map((faq) => (
                <div key={faq.q} className="p-4 bg-slate-50 dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700">
                  <h3 className="font-semibold text-lg text-slate-800 dark:text-white">{faq.q}</h3>
                  <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Final CTA Section */}
        <section className="py-16 md:py-24 text-center bg-slate-100 dark:bg-slate-950">
          <div className="container mx-auto px-4 sm:px-6">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-6">
                Ready to Claim Your Victory Royale Logo?
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-400 mb-10 max-w-xl mx-auto">
              Stand out in the lobby and on stream. Design a unique, AI-powered Fortnite logo that’s all yours.
            </p>
            <button
              onClick={handleStartDesigning}
              className="px-8 py-3 bg-purple-600 hover:bg-purple-700 text-white font-semibold rounded-lg text-md transition-colors duration-300 shadow-md hover:shadow-lg dark:bg-cyan-500 dark:hover:bg-cyan-600 dark:text-slate-900"
              id="cta-final-fortnite-to-tool"
            >
              Make My Fortnite Logo Now!
            </button>
          </div>
        </section>
      </main>
    </>
  );
};

export default FortniteLogoLandingPage;