// src/pages/free-fire-logos.tsx
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { Button } from "~/component/Button";
import { FaChevronRight, FaGamepad, FaDownload, FaPaintBrush, FaUsers } from "react-icons/fa"; // Example Icons

// This array should showcase your best Free Fire-style logo examples.
// Generate these using your tool and relevant style prompts.
const freeFireStyleExamples = [
  // ** REPLACE these with ACTUAL paths to your best Free Fire-style example images **
  { src: "/styles/s711e.webp", alt: "Free Fire DJ Alok mascot logo with glowing headphones and neon waves" },
  { src: "/styles/s712e.webp", alt: "Chrono Free Fire logo with futuristic armor and blue energy shield" },
  { src: "/styles/s713e.webp", alt: "Captain Booyah (K) Free Fire mascot logo with glowing gold jacket" },
  { src: "/styles/s714e.webp", alt: "Jota Free Fire mascot logo in combat stance with dual guns" },
  { src: "/styles/s715e.webp", alt: "Kelly Free Fire logo with high-speed sprint and neon yellow streaks" },
  { src: "/styles/s716e.webp", alt: "Dimitri Free Fire mascot logo with DJ console and soundwave effects" },
  { src: "/styles/s717e.webp", alt: "Hayato Free Fire samurai mascot logo with glowing katana and flames" },
  { src: "/styles/s720e.webp", alt: "Moco Free Fire hacker mascot logo with neon green hair and cyber effects" },
];

const FreeFireLogoLandingPage: NextPage = () => {
  const router = useRouter();

  const handleStartDesigning = () => {
    // Navigate to the tool, ideally pre-filtered for Free Fire styles
    // Example: /gaming-logo-tool?category=By+Game+Title&subcategory=Free+Fire
    void router.push("/gaming-logo-maker");
  };

  return (
    <>
      <Head>
        <title>Free Fire Logo Maker - AI FF Gaming & Clan Logos | GamingLogoAI</title>
        <meta
          name="description"
          content="Create a custom Free Fire logo for your guild, YouTube channel, or profile with our AI logo maker. Design unique FF gaming logos, character logos, and 3D styles in seconds. Get 1 free credit to start!"
        />
        <meta name="keywords" content="free fire logo maker, ff logo, garena free fire logo, gaming logo free fire, free fire clan logo, free fire youtube logo, ff gaming logo, free fire esports logo, custom ff logo" />
        <link rel="canonical" href="https://gaminglogoai.com/free-fire-logos" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white dark:bg-slate-950 text-slate-800 dark:text-slate-200 overflow-x-hidden">
        {/* Hero Section */}
        <section className="relative py-16 md:py-24 text-center text-white overflow-hidden">
          <Image src="/images/features/free-fire-hero-bg.webp" alt="Action-packed Free Fire inspired background" layout="fill" objectFit="cover" quality={75} className="z-0 opacity-30 dark:opacity-25" priority />
          <div className="absolute inset-0 bg-gradient-to-br from-orange-800/80 via-red-900/90 to-slate-900/95 z-10"></div>
          
          <div className="container mx-auto px-4 sm:px-6 relative z-20">
            <Image
              src="/styles/s718e.webp"
              alt="An epic Free Fire gaming logo generated by AI"
              width={150}
              height={150}
              className="mx-auto mb-6 rounded-lg shadow-2xl border-4 border-orange-400/80"
              priority
            />
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold mb-6 leading-tight drop-shadow-lg [text-shadow:_2px_2px_4px_rgb(0_0_0_/_50%)]">
              AI <span className="text-orange-400">Free Fire Logo</span> Maker
            </h1>
            <p className="text-lg sm:text-xl text-slate-200 max-w-3xl mx-auto mb-10 drop-shadow-sm">
              Instantly design a legendary logo for your Free Fire guild, squad, or YouTube channel. Create a unique look that dominates the battlefield!
            </p>
            <div className="flex justify-center">
                <Button
                onClick={handleStartDesigning}
                variant="primary"
                size="lg"
                className="text-lg font-bold shadow-xl hover:shadow-orange-400/60"
                id="cta-hero-ff-to-tool"
                >
                Design Your FF Logo Now<FaChevronRight className="inline ml-2 -mr-1" />
                </Button>
            </div>
            <p className="mt-4 text-xs text-slate-400">Sign up to claim your free credit. No design skills needed!</p>
          </div>
        </section>

        {/* Example Gallery Section */}
        <section className="py-16 md:py-20 bg-white dark:bg-slate-900">
          <div className="container mx-auto px-4 sm:px-6">
            <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12 text-slate-900 dark:text-white">
              AI-Generated <span className="text-purple-600 dark:text-cyan-400">FF Gaming Logo</span> Ideas
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {freeFireStyleExamples.map((example, index) => (
                <div key={index} className="group relative rounded-lg shadow-lg overflow-hidden aspect-square">
                  <Image src={example.src} alt={example.alt} layout="fill" objectFit="cover" className="transition-transform duration-500 group-hover:scale-110" />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section className="py-16 md:py-20 bg-slate-50 dark:bg-slate-950">
            <div className="container mx-auto px-4 sm:px-6">
                <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12 text-slate-900 dark:text-white">
                    Create Your Custom <span className="text-purple-600 dark:text-cyan-400">Free Fire Logo</span> in Seconds
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
                    {[
                        { title: "1. Enter Your Name", desc: "Type your guild name, gamer tag, or channel name.", icon: <FaGamepad className="h-10 w-10 mx-auto mb-3"/> },
                        { title: "2. Pick a FF Style", desc: "Choose from dozens of styles inspired by Free Fire characters, skins, and themes.", icon: <FaPaintBrush className="h-10 w-10 mx-auto mb-3"/> },
                        { title: "3. Generate & Download", desc: "Our AI creates your logos instantly. Download your favorite design!", icon: <FaDownload className="h-10 w-10 mx-auto mb-3"/> }
                    ].map(step => (
                        <div key={step.title} className="p-6 bg-white dark:bg-slate-800 rounded-lg shadow-lg">
                            <div className="text-purple-600 dark:text-cyan-400">{step.icon}</div>
                            <h3 className="text-xl font-semibold my-2 text-slate-800 dark:text-white">{step.title}</h3>
                            <p className="text-sm text-slate-600 dark:text-slate-400">{step.desc}</p>
                        </div>
                    ))}
                </div>
                 <div className="text-center mt-12 flex justify-center">
                    <Button onClick={handleStartDesigning} variant="accent" size="lg" className="font-bold shadow-lg">
                        Start with Your Free Credit
                    </Button>
                </div>
            </div>
        </section>
        
        {/* FAQ Section (Crucial for SEO) */}
        <section className="py-16 md:py-20 bg-white dark:bg-slate-900">
          <div className="container mx-auto max-w-3xl px-4 sm:px-6">
            <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12 text-slate-900 dark:text-white">
              Your <span className="text-purple-600 dark:text-cyan-400">Free Fire (FF) Logo</span> Questions
            </h2>
            <div className="space-y-6">
              {[
                {
                  q: "How can I get a Free Fire logo for free?",
                  a: "You're in the right place! Every new user at GamingLogoAI gets 1 free credit upon signing up. You can use this credit to generate and download your first custom Free Fire logo at no cost. It's a great way to try our AI logo maker."
                },
                {
                  q: "Can I use this tool as a Free Fire guild logo maker?",
                  a: "Yes, absolutely! Our tool is perfect for creating a unique logo for your Free Fire guild or squad. Just enter your guild name and choose from our many aggressive, cool, and mascot-style designs to find the perfect emblem for your team."
                },
                {
                  q: "Is this good for making a Free Fire YouTube channel logo?",
                  a: "Definitely. You can generate logos in different shapes and sizes, making it easy to create a perfect logo for your Free Fire YouTube channel profile picture and channel art. The high-resolution downloads ensure your branding looks sharp."
                },
                {
                  q: "Can I create a 3D Free Fire logo?",
                  a: "Yes, many of our art styles can generate logos with a 3D effect. Look for styles in our library labeled '3D', 'Emblem', or 'Mascot' to create an impactful 3D Free Fire logo that stands out."
                }
              ].map((faq) => (
                <div key={faq.q} className="p-4 bg-slate-50 dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700">
                  <h3 className="font-semibold text-lg text-slate-800 dark:text-white">{faq.q}</h3>
                  <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Final CTA Section */}
        <section className="py-16 md:py-24 text-center bg-slate-100 dark:bg-slate-950">
          <div className="container mx-auto px-4 sm:px-6">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-6">
                Ready for Your Booyah! Moment?
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-400 mb-10 max-w-xl mx-auto">
              A great logo is your first victory. Create a legendary Free Fire logo that stands out in every match and on every stream.
            </p>
            <div className="flex justify-center">
                <Button
                    onClick={handleStartDesigning}
                    variant="primary"
                    size="lg"
                    className="font-bold text-lg shadow-xl"
                id="cta-final-ff-to-tool"
                >
                Get Your Free Fire Logo Now
                </Button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default FreeFireLogoLandingPage;